### ISSUE TITLE
ATGC Content 0%

### ISSUE THREAD

**Issue by markscherz** [iTaxoTools/TaxIGui#1] opened 2023-03-06 14:50 UTC
Summary stats given in stats > species.tsv should give 'percentage of base N' where N is A, T, G, or C, each in a separate column. These values are consistently 0% across the board in my trials. Percentage ambiguity codes is given as 1% for all samples, but I guess this is supposed to be 100%, and that it is parsing all my bases as ambiguity codes. 

Input file attached
[16S_5_incl_Potsdam_iTaxoTools_AClade.txt](https://github.com/iTaxoTools/TaxIGui/files/10899424/16S_5_incl_Potsdam_iTaxoTools_AClade.txt)

**Comment by StefanPatman** [comment] 2023-03-07 17:38
Thank you for reporting this bug. Unfortunately, I was not able to reproduce it.

Did you use any non-default options? What is your operating system (Windows/Linux/macOS)? Did you run from source or from a compiled executable? Were the other results correct, or did the program fail to process the sequences for all functions?

Perhaps this is an encoding issue and GitHub modified the file when you uploaded. What happens if you download your attached file and try again?

**Comment by markscherz** [comment] 2023-03-07 20:21
No non-default options. Versus All. Already aligned. MacOS Ventura 13.2.1. Run from the compiled executable GUI. 
Running params:
<img width="1676" alt="Screenshot 2023-03-07 at 21 17 26" src="https://user-images.githubusercontent.com/46906676/223542529-81290419-d013-4e66-88a9-f1170690afe9.png">

I tried downloading the attached file and running it again, and still get this issue. 
The other results (distances, sequence lengths, etc.) seem to be correct; just ATGC percentages, GC content percentage, and percentage of ambiguity codes are spurious.
Here is the species stats results output file (changed from .tsv to .txt because github doesn't accept .tsvs)
[species.txt](https://github.com/iTaxoTools/TaxIGui/files/10913670/species.txt)

**Comment by StefanPatman** [comment] 2023-03-09 14:11
Thank you for elaborating. This bug only appears when calculating statistics for already aligned, lower-case sequences. This is now fixed and will be included in the next executable. For now, you may work around this by providing upper-case sequences as input for the current executable.

Working on this dataset also revealed another bug when selecting the option "Distances as percentages". This was also fixed.

**Closed as completed** 2023-03-21 13:28 UTC
